### ISSUE TITLE
Missing Mats for Macroz

### ISSUE THREAD

**Issue by ohlawdie** [flow0284/MillButton#4]
Hey superb addition for a budding inscript-er...whiptail and certain herbs don't seem to be an option for the macro? Also, is this addon using a framework like Super Duper Macro or LongMacros to deal with the macro character limit or are we unlimited in what we can do? Thanks!

**Comment by flow0284** [comment]
Just select in the options the herbs you want to mill and use the millbutton macro. there is nothing else todo
